server:
    port: 8081
spring:
    application:
        name: Customer
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 552588647
        url: jdbc:mysql://localhost:3306/streaming
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true
